Work around discrepancy between MSVC 19.27 and 19.28 about static const member definition
https://developercommunity2.visualstudio.com/t/discrepancy-between-msvc-1927-vs-1928-about-static/1255338

NOTE: We can not use C++17 inline variable as a workaround suggesed in the issue report,
because sol2 does not compile in C++17 mode:

   third_party/sol2/sol2/sol.hpp: error C2039: 'object_type': is not a member of...

So, we still build osrm-backend as C++14.

(cherry picked from commit 360bf4d2e425ec7a0ebcf1bd9429ad7e5153137c in cadcorp/5.24 branch)